for b in range (2):
    print(
        "integer b"+str(b)+";\n"
        "integer c"+str(b)+";\n"
        "logic [5:0] k"+str(b)+";\n"
        "blwbys_ff @(posedge clk or posedge rst) begin//調控第一個PE小區的Num\n"
        "    if(rst)begin\n"
        "        for (b"+str(b)+"=1 ; b"+str(b)+"<16 ; b"+str(b)+"=b"+str(b)+"+1) begin\n"
        "            OSISnum["+str(b)+"][b"+str(b)+"]=("+str(b)+"*kernelsize/(6-kernelsize)*6)+("+str(b)+"*kernelsize%(6-kernelsize));\n"
        "            OSWSnum["+str(b)+"][b"+str(b)+"]=("+str(b)+"*kernelsize/(6-kernelsize)*6)+("+str(b)+"*kernelsize%(6-kernelsize));\n"
        "            k"+str(b)+"<=0;\n"
        "            c"+str(b)+"<=0;\n"
        "        end\n"
        "    end else begin\n"
        "        if(state["+str(b)+"])begin\n"
        "            for (b"+str(b)+"=1 ; b"+str(b)+"<16 ; b"+str(b)+"=b"+str(b)+"+1) begin\n"
        "                if(b"+str(b)+"<=OS_counter["+str(b)+"])begin//換到他輸入\n"
        "                    if(size-(k1+OS_counter["+str(b)+"]-b1) < kernelsize)begin\n"
        "                       OSISnum["+str(b)+"][b"+str(b)+"] <= k"+str(b)+"+OS_counter["+str(b)+"]-b"+str(b)+"+c"+str(b)+";\n"
        "                       OSWSnum["+str(b)+"][b"+str(b)+"] <= k"+str(b)+"+OS_counter["+str(b)+"]-b"+str(b)+"+c"+str(b)+";\n"
        "                       c"+str(b)+"=c"+str(b)+"+kernelsize-1;\n"
        "                    end else begin\n"
        "                       OSISnum["+str(b)+"][b"+str(b)+"] <= k"+str(b)+"+OS_counter["+str(b)+"]-b"+str(b)+"+c"+str(b)+";\n"
        "                       OSWSnum["+str(b)+"][b"+str(b)+"] <= k"+str(b)+"+OS_counter["+str(b)+"]-b"+str(b)+"+c"+str(b)+";\n"
        "                    end\n"
        "                end\n"
        "                else if(b"+str(b)+" < OS_counter["+str(b)+"])begin\n"
        "                if(((OSISnum[b"+str(b)+"][b"+str(b)+"])-b"+str(b)+")%kernelsize==0)begin//如果三個要換行\n"
        "                   OSISnum["+str(b)+"][b"+str(b)+"] <= OSISnum["+str(b)+"][b1]+6-kernelsize+1;\n"
        "                   OSWSnum["+str(b)+"][b"+str(b)+"] <= OSWSnum["+str(b)+"][b"+str(b)+"]+6-kernelsize+1;\n"
        "                end else begin\n"
        "                   OSISnum["+str(b)+"][b"+str(b)+"] <= OSISnum["+str(b)+"][b"+str(b)+"]+1;\n"
        "                   OSWSnum["+str(b)+"][b"+str(b)+"] <= OSWSnum["+str(b)+"][b"+str(b)+"]+1;\n"
        "                end\n"
        "                end\n"
        "                else begin\n"
        "                   OSISnum["+str(b)+"][b"+str(b)+"] <= OSISnum["+str(b)+"][b"+str(b)+"];\n "
        "                   OSWSnum["+str(b)+"][b"+str(b)+"] <= OSWSnum["+str(b)+"][b"+str(b)+"];\n "
        "               end\n"
        "            end\n"
        "        end else begin\n"
        "            OSISnum["+str(b)+"][b"+str(b)+"]=("+str(b)+"*kernelsize/(6-kernelsize)*6)+("+str(b)+"*kernelsize%(6-kernelsize));\n"
        "            OSWSnum["+str(b)+"][b"+str(b)+"]=("+str(b)+"*kernelsize/(6-kernelsize)*6)+("+str(b)+"*kernelsize%(6-kernelsize));\n"
        "            k"+str(b)+"<=0;\n"
        "            c"+str(b)+"<=0;\n"
        "        end\n"
        "    end\n"
        "end\n")
