#OSISnum[PE part]
#OSISnum[Layer][PE part]
a=16#a是SRAM的尺寸
for b in range (1):
    print(
    "integer a0;\n"
    "integer b0;//\n"
    "integer c0;//用來記錄要不要換行\n"
    "integer d0[15:0][15:0];//用來看是不是數到三個數需要換行了 d0[PE part][inside]\n"
    "integer r;\n"
    "always_ff @(posedge clk or posedge rst) begin//調控第一個PE小區的Num\n"
    "    if(rst)begin\n"
    "        for ( r=0 ; r<16 ; r=r+1) begin\n"    
    "            OSISnum[r][0]=(0*kernelsize[r]/("+str(a)+"-kernelsize[r])*"+str(a)+")+(kernelsize[r]%("+str(a)+"-kernelsize[r]));\n"
    "            OSWSnum[r][0]=(0*kernelsize[r]/("+str(a)+"-kernelsize[r])*"+str(a)+")+(kernelsize[r]%("+str(a)+"-kernelsize[r]));\n"
    "            c0<=0;\n"
    "            for (a0=0 ; a0<16 ; a0=a0+1) begin\n"
    "                d0[a0][r]<=0;\n"
    "            end\n"
    "        end\n")
    print(
    "    end else begin\n"
    "        for ( r=0 ; r<16 ; r=r+1) begin\n"
    "            if(state[r])begin\n"
    "                for (b0=0 ; b0<16 ; b0=b0+1) begin\n"
    "                    if(b0 == OS_counter[r] && b0!=0)begin//換到他輸入\n"
    "                        if(("+str(a)+"-(OSISnum[r][b0-1]))%kernelsize[r]==0)begin\n"
    "                            OSISnum[r][b0] <= OSISnum[r][b0-1]+OS_counter[r]-b0+c0;\n"
    "                            OSWSnum[r][b0] <= OSwSnum[r][b0-1]+OS_counter[r]-b0+c0;\n"
    "                            c0=c0+kernelsize[r]-1;\n"
    "                            d0[r][b0]<=d0[r][b0]+1;\n"
    "                        end else begin\n"
    "                            OSISnum[r][b0] <= OSISnum[r][b0-1]+OS_counter[r]-b0+c0;\n"
    "                            OSWSnum[r][b0] <= OSWSnum[r][b0-1]+OS_counter[r]-b0+c0;\n"
    "                            d0[r][b0]<=d0[r][b0]+1;\n"
    "                        end\n"
    "                    end\n"
    "                    else if(b0 < OS_counter[0] || b0==0)begin\n"
    "                        if((d0[r][b0]+1)%3==0)begin//如果三個要換行\n"
    "                            OSISnum[r][b0] <= OSISnum[r][b0]+"+str(a)+"-kernelsize[r]+1;\n"
    "                            OSWSnum[r][b0] <= OSWSnum[r][b0]+"+str(a)+"-kernelsize[r]+1;\n"
    "                            d0[r][b0]<=d0[r][b0]+1;\n"
    "                        end else begin\n"
    "                            OSISnum[r][b0] <= OSISnum[r][b0]+1;\n"
    "                            OSWSnum[r][b0] <= OSWSnum[r][b0]+1;\n"
    "                            d0[r][b0]<=d0[r][b0]+1;\n"
    "                        end\n"
    "                    end\n"
    "                    else begin\n"
    "                        OSISnum[r][b0] <= OSISnum[r][b0];\n"
    "                        OSWSnum[r][b0] <= OSWSnum[r][b0];\n"
    "                    end\n"
    "                end\n"
    "            end else begin\n"
    "                for (a0=0 ; a0<16 ; a0=a0+1) begin\n"
    "                    OSISnum[r][a0]=(0*kernelsize[r]/("+str(a)+"-kernelsize[r])*"+str(a)+")+(kernelsize[r]%("+str(a)+"-kernelsize[r]));\n"
    "                    OSWSnum[r][a0]=(0*kernelsize[r]/("+str(a)+"-kernelsize[r])*"+str(a)+")+(kernelsize[r]%("+str(a)+"-kernelsize[r]));\n"
    "                    c0<=0;\n"
    "                    d0[r][a0]<=0;\n"
    "                end\n"
    "            end\n"
    "        end\n"
    "    end\n"
    "end\n")

